### ISSUE TITLE
Show answer from Player in Truth or Dare to everyone 

### ISSUE THREAD

**Issue by Aynril** [Herobone/Sober-Sailor#106]
Currently, the answer from the player in the Truth or Dare gamemode is not being shown and the answer is kind of secret and only recognizable through looking at the sips of the person. 
Feature needs to implement: 
- Answer is being shown to everybody in the room
- Count of sips is being shown to everybody in case the player decides not to do the task

**Comment by Herobone** [comment]
Added in the evaluation Scoreboard
