### ISSUE TITLE
Let me introduce to you: MEMES!

### ISSUE THREAD

**Issue by Aynril** [Herobone/Sober-Sailor#50]
- [x] Add random meme from r/dankmemes at loading screen or when done with choosing task (when time is not up)
- [ ] Support for a higher number of subreddits

**Comment by Herobone** [comment]
App mostly has no loading time, and displaying a meme would definitely not speed that up

**Comment by Aynril** [comment]
Meme could be displayed after answering a question and during the time bar still running down.

**Comment by Herobone** [comment]
Added along with cats and dogs in f9198f08003e6107a05d680ab447a52a69887d72
